---
title: "RedditAnalysis"
author: "Frederik Mann"
date: "29 6 2021"
output:
  html_document: default
---

```{r setup, echo=FALSE, cache=FALSE}
knitr::opts_chunk$set(echo = TRUE)
Sys.setenv(LANG = "en")
```

## Posts

```{r libs}
library(pacman)
p_load(RColorBrewer, # color pallets
       ggplot2, # reportable graphs
       cowplot, # arranges ggplot graphs nicely
       stargazer,
       MASS,
       DescTools,
       plyr,
       moments) 
```

### Import data set
```{r import, cache=TRUE}
df2_berlin <- read.csv("data/posts/posts_berlin_2020.csv")
df2_germany <- read.csv("data/posts/posts_de_2020.csv")
df2_europe <- read.csv("data/posts/posts_europe_2020.csv")
df2 <- rbind(df2_berlin, df2_germany, df2_europe) #df2 so it can be run in the same environment
```

### Inspect
```{r inspect}
df2$over_18 <- as.logical(df2$over_18)
df2$locked <- as.logical(df2$locked)
df2$is_video <- as.logical(df2$is_video)
df2$is_original_content <- as.logical(df2$is_original_content)
df2$stickied <- as.logical(df2$stickied)
df2$subreddit <- as.factor(df2$subreddit)

#removing unused columns
df2$permalink <- NULL
df2$author_fullname <- NULL
df2$title <- NULL
df2$url <- NULL
df2$is_original_content <- NULL
df2$author_flair_text <- NULL
df2$is_video <- NULL
df2$link_flair_richtext <- NULL
df2$domain <- NULL
df2$over_18 <- NULL
df2$total_awards_received <- NULL
df2$num_comments <- NULL
df2$epoch <- NULL

str(df2)
```



### Preprocess: Treat missing values, if applicable
```{r preprocess}
#Treating missing values
nrow(df2)

df2$author[df2$author == ""] <- NA

df2$deleted <- ifelse(df2$selftext == "[deleted]", TRUE, FALSE)
df2$removed <- ifelse(df2$selftext == "[removed]", TRUE, FALSE)

print("Duplicates")
sum(duplicated(df2$id))
(sum(duplicated(df2$id))) / nrow(df2)

df2 <-df2[!duplicated(df2$id), ]

print("NAs")
# Track down variables with missing values
sum(is.na(df2))
colSums(is.na(df2))

# Check the percentage of missing values in the data set
(nrow(df2) - nrow(na.omit(df2))) / nrow(df2)


sum(df2$stickied == TRUE)
(sum(df2$stickied == TRUE)) / nrow(df)

df2 <- df2[!(df2$stickied == TRUE),]

nrow(df2)

```

### Preprocess: Treat missing values, if applicable
```{r precalculations}
#Interval calculation
to_interval <- function(anchor.date, future.date, interval.days){
  return(round(as.integer(future.date - anchor.date) / interval.days, 0) + 1)
}

df2$date <- as.Date(df2$datetime)

df2$interval <- to_interval(as.Date('2020-01-01'), 
                          df2$date, 14)

df2$interval <- factor(df2$interval)

df2$score_adjusted <- log10(pmax(abs(df2$score), 1))

df2$deleted <- ifelse(df2$selftext == "[deleted]", TRUE, FALSE)

df2$removed <- ifelse(df2$selftext == "[removed]", TRUE, FALSE)

```

### stats_dataset
```{r stats_dataset}
print("all")
nrow(df2[df2$locked == TRUE,]) / nrow(df2)
nrow(df2[df2$removed == TRUE,]) / nrow(df2)
nrow(df2[df2$deleted == TRUE,]) / nrow(df2)
nrow(df2[df2$removed == FALSE & df2$deleted == FALSE & is.na(df2$author),]) / nrow(df2)

for(subreddit in c("berlin", "de", "europe")){
  print(subreddit)
  writeLines(paste("Locked %:\t\t",nrow(df2[df2$locked == TRUE & df2$subreddit == subreddit,]) / nrow(df2)))
  writeLines(paste("Removed %:\t\t",nrow(df2[df2$removed == TRUE & df2$subreddit == subreddit,]) / nrow(df2)))
  writeLines(paste("Deleted %:\t\t",nrow(df2[df2$deleted == TRUE & df2$subreddit == subreddit,]) / nrow(df2)))
  writeLines(paste("Acccount deleted %:\t",nrow(df2[df2$removed == FALSE & df2$deleted == FALSE & is.na(df2$author) & df2$subreddit == subreddit,]) / nrow(df2)))
}
```

### Preinspection
```{r preinspection}
data.frame(table(df2$month))

df2wi <- data.frame(table(df2$interval))
df2wi


tbl <- with(df2, table(subreddit, interval))
ggplot(as.data.frame(tbl), aes(factor(interval), Freq, fill = subreddit)) +     
  geom_col(position = 'dodge')

summary(df2$score)
summary(df2$score_adjusted)
ggplot(df2[df2$score < 1000 & df2$score > 10,], aes(score)) +
  geom_freqpoly(binwidth = 5)


ggplot(df2, aes(score_adjusted)) +
  geom_freqpoly(binwidth = 0.1)

```

### Calculations
```{r calculations}

Gini(df2wi$Freq)

nrow(df2)
df2_with_acc <- na.omit(df2)
nrow(df2_with_acc)

 
id <- 0
df2_subs <- data.frame(
                 id = factor(),
                 interval=character(),
                 gini_post_dist=double(),
                 gini_score_dist=double(),
                 gini_score_dist_adjusted = double(),
                 subreddit=factor(levels = levels(df2_with_acc$subreddit)),
                 contributors = integer(),
                 total_posts = integer(),
                 turnover = double(),
                 stringsAsFactors=TRUE
                 )


for (subreddit in levels(df2_with_acc$subreddit)){
  df2_subreddit <- df2_with_acc[df2_with_acc$subreddit == subreddit, ]
  df2_author_prev_interval <- NULL
  for (interval in head( unique(df2_subreddit$interval), -1)){

    df2_interval <- df2_subreddit[df2_subreddit$interval == interval, ]
    
    df2_author_posts <- count(df2_interval, vars = "author")
    
    df2_author_score <- aggregate(df2_interval$score, by=list(author=df2_interval$author), FUN=sum)
    names(df2_author_score)[names(df2_author_score) == 'x'] <- 'sum'
    
    df2_author_score_adjusted <- aggregate(df2_interval$score_adjusted, by=list(author=df2_interval$author), FUN=sum)
    names(df2_author_score_adjusted)[names(df2_author_score_adjusted) == 'x'] <- 'sum_adjusted'
    
    df2_author <- merge(df2_author_posts, df2_author_score, by="author")
    df2_author <- merge(df2_author, df2_author_score_adjusted, by="author")
    
    df2_author$score_per_post <- df2_author$sum / df2_author$freq
    df2_author$score_per_post_adjusted <- df2_author$sum_adjusted / df2_author$freq
    df2_author$perc_of_total_post <- df2_author$freq / length(df2_author)
    
    gini_score_dist <- Gini(df2_author$score_per_post)
    gini_score_adjusted_dist <- Gini(df2_author$sum_adjusted)
    
    gini_post_dist <- Gini(df2_author$freq)
    
    
    turnover <- double()
    if(is.null(df2_author_prev_interval)){
      turnover <- NA
    }
    else{
      df2_author_intersect <- intersect(df2_author$author, df2_author_prev_interval)
      turnover <- 1 - (length(df2_author_intersect) / length(df2_author$author))
    }
    
    df2_sub <- data.frame(
                   id=id,
                   interval=interval,
                   gini_post_dist=gini_post_dist,
                   gini_score_dist=gini_score_dist,
                   gini_score_adjusted_dist = gini_score_adjusted_dist,
                   subreddit=subreddit,
                   contributors = length(unique(df2_interval$author)),
                   total_posts = length(df2_interval$id),
                   turnover = turnover,
                   stringsAsFactors=TRUE
                   )
    id <- id + 1
    df2_author_prev_interval <- df2_author$author
    df2_subs <- rbind(df2_subs, df2_sub)
  }
}

df2_subs$log_contributors <- log(df2_subs$contributors)

df2_subs$is_berlin <- df2_subs$subreddit == "berlin"
df2_subs$is_de <- df2_subs$subreddit == "de"
df2_subs$is_europe <- df2_subs$subreddit == "europe"

df2_subs$interval <-as.numeric(as.character(df2_subs$interval))

```

### Data Visualisation
Used to check for incomplette data or outliers
```{r visualisation, eval = TRUE}
subreddit_colors <- c("berlin" = "#f8766d", "de" = "#00ba38", "europe" ="#619cff")



ggplot(df2_subs, aes(x = reorder(id, contributors), y = contributors, fill = subreddit)) +
  geom_bar(stat = "identity", binwidth=0, width=1) +
  scale_fill_manual(name = "Subreddit", values=subreddit_colors) +
  ggtitle("UC Distribution by Groups")+
  ylab("UC") +
  xlab("Datapoints ordered by UC")+
  theme(axis.text.x=element_blank(), #remove x axis labels
        axis.ticks.x=element_blank(), #remove x axis ticks
        )

ggsave(path = "posts_files/figure-svg/", filename = "datapoint_ordered_uc.svg", device='svg')
ggsave(path = "posts_files/figure-png/", filename = "datapoint_ordered_uc.png", device='png')


str(df2_subs)
summary(df2_subs)

ggplot(df2_subs, aes(x=interval, y=gini_post_dist, group = subreddit, color = subreddit)) +
  geom_point() 

ggplot(df2_subs, aes(x=interval, y=gini_score_adjusted_dist, group = subreddit, color = subreddit)) +
  geom_point() 

ggplot(df2_subs, aes(x=interval, y=contributors, group = subreddit, color = subreddit)) +
  geom_point()

ggplot(df2_subs, aes(x=interval, y=total_posts, group = subreddit, color = subreddit)) +
  geom_point()



ggplot(df2_subs[!is.na(df2_subs$turnover),], aes(x=interval, y=turnover, group = subreddit, color = subreddit)) +
  geom_point()
```

### Calculated Subreddit Data Set Stats
```{r stats_subreddits}
mean(df2_subs$contributors)
sd(df2_subs$contributors)



print("Min/Max")
min(df2_subs$contributors)
max(df2_subs$contributors)

print("is_berlin")    
mean(df2_subs$contributors[df2_subs$is_berlin])
sd(df2_subs$contributors[df2_subs$is_berlin])


print("is_de")    
mean(df2_subs$contributors[df2_subs$is_de])
sd(df2_subs$contributors[df2_subs$is_de]) 

print("is_europe")
mean(df2_subs$contributors[df2_subs$is_europe])
sd(df2_subs$contributors[df2_subs$is_europe]) 

print("skewness")
skewness(df2_subs$contributors)
kurtosis(df2_subs$contributors)

max(df2_subs$interval)
max(df2_subs$log_contributors)
min(df2_subs$log_contributors)

df2_subs_berlin <- df2_subs[df2_subs$is_berlin == TRUE,]
mean(df2_subs_berlin$gini_score_dist)
mean(df2_subs_berlin$contributors)

for(sub in c("berlin", "de", "europe")){
  print(sub)
  print(length(unique(df2$author[df2$subreddit == sub])))
  print(length(df2$author[df2$subreddit == sub]))
}
```


```{r models_turnover}
ggplot(df2_subs[!is.na(df2_subs$turnover),], aes(x=contributors, y=turnover)) +
  geom_point(aes(color = factor(subreddit))) +
  geom_smooth(method='lm', formula= y~x) +
  ylim(0,1) +
  scale_x_continuous(trans='log2') +
  labs(title = "UC predicting turnover", x = "Unique contributor/Week (log2)", y = "Turnover", color = "Subreddits")

ggsave(path = "posts_files/figure-svg/", filename = "turnover.svg", device='svg')
ggsave(path = "posts_files/figure-png/", filename = "turnover.png", device='png')
  

lm_model <- lm(turnover ~ log_contributors, data = df2_subs)
summary(lm_model)

lm_model <- lm(turnover ~ log_contributors + interval, data = df2_subs)
summary(lm_model)

lm_model <- lm(turnover ~ log_contributors + interval + is_berlin + is_de, data = df2_subs)
summary(lm_model)

lm_model <- lm(turnover ~ log_contributors * is_berlin + log_contributors * is_de + is_berlin + is_de, data = df2_subs)
summary(lm_model)

print("Predicting Turnover when looking at all and each group")
lm_model <- lm(turnover ~ log_contributors + interval, data = df2_subs)
summary(lm_model)

lm_model <- lm(turnover ~ log_contributors + interval, data = df2_subs[df2_subs$is_berlin,])
summary(lm_model)

lm_model <- lm(turnover ~ log_contributors + interval, data = df2_subs[df2_subs$is_de,])
summary(lm_model)

lm_model <- lm(turnover ~ log_contributors + interval, data = df2_subs[df2_subs$is_europe,])
summary(lm_model)

"
agg <- aggregate(df2_with_acc$score, by=list(author=df2_with_acc$author), FUN=sum)
ggplot(agg, aes(x=author, y=x)) + geom_point()
"

```

### Models
```{r models_participation}
mean(df2_subs$gini_post_dist)

ggplot(df2_subs, aes(x=log_contributors, y=gini_post_dist)) +
  geom_point(aes(color = factor(subreddit))) +
  geom_smooth(method='lm', formula= y~x) +
  ylim(0,1) +
  labs(title = "UC predicting distribution of participation", x = "Unique contributor(log2)", y = "Distribution of participation", color = "Subreddits")

ggsave(path = "posts_files/figure-svg/", filename = "gini_distribution_participation.svg", device='svg')
ggsave(path = "posts_files/figure-png/", filename = "gini_distribution_participation.png", device='png')

lm_model <- lm(gini_post_dist ~ log_contributors + interval, data = df2_subs)
summary(lm_model)

lm_model <- lm(gini_post_dist ~ log_contributors + interval, data = df2_subs[df2_subs$is_berlin,])
summary(lm_model)

lm_model <- lm(gini_post_dist ~ log_contributors + interval, data = df2_subs[df2_subs$is_de,])
summary(lm_model)

lm_model <- lm(gini_post_dist ~ log_contributors + interval, data = df2_subs[df2_subs$is_europe,])
summary(lm_model)

#lm_model <- lm(gini_post_dist ~ log_contributors + interval + is_berlin + is_de , data = df2_subs)
#summary(lm_model)
```

```{r stats_visibility}
nrow(df2[df2$score_adjusted == 0,])
nrow(df2[df2$score_adjusted == 0,]) / nrow(df2)



print("all")
min(df2_subs$gini_score_adjusted_dist)
max(df2_subs$gini_score_adjusted_dist)
mean(df2_subs$gini_score_adjusted_dist)
sd(df2_subs$gini_score_adjusted_dist)

print("is_berlin")    
mean(df2_subs$gini_score_adjusted_dist[df2_subs$is_berlin])
sd(df2_subs$gini_score_adjusted_dist[df2_subs$is_berlin])
nrow(df2[df2$score_adjusted == 0 & df2$subreddit == "berlin",]) / nrow(df2[df2$subreddit == "berlin",])


print("is_de")    
mean(df2_subs$gini_score_adjusted_dist[df2_subs$is_de])
sd(df2_subs$gini_score_adjusted_dist[df2_subs$is_de])
nrow(df2[df2$score_adjusted == 0 & df2$subreddit == "de",]) / nrow(df2[df2$subreddit == "de",])

print("is_europe")
mean(df2_subs$gini_score_adjusted_dist[df2_subs$is_europe])
sd(df2_subs$gini_score_adjusted_dist[df2_subs$is_europe])
nrow(df2[df2$score_adjusted == 0 & df2$subreddit == "europe",]) / nrow(df2[df2$subreddit == "europe",])
```

```{r models_visibility}

ggplot(df2_subs[df2_subs$interval!=1,], aes(x=contributors, y=gini_score_adjusted_dist)) +
  geom_point(aes(color = factor(subreddit))) +
  geom_smooth(method='lm', formula= y~x) +
  ylim(0,1) +
  scale_x_continuous(trans='log2') +
  labs(title = "UC predicting Concentration of Visibility",
       x = "Unique contributor/Interval (log2)",
       y = "Concentration of Visibility",
       color = "Subreddits")

ggsave(path = "posts_files/figure-svg/", filename = "gini_distribution_score.svg", device='svg')
ggsave(path = "posts_files/figure-png/", filename = "gini_distribution_score.png", device='png')

print("Predicting C.o.Visibility Basic")
lm_model <- lm(gini_score_adjusted_dist ~ log_contributors, data = df2_subs)
summary(lm_model)

print("Predicting C.o.Visibility with Group test")
lm_model <- lm(gini_score_adjusted_dist ~ log_contributors + interval + is_berlin + is_de, data = df2_subs)
summary(lm_model)

print("Predicting C.o.Visibility when looking at all and each group")
lm_model <- lm(gini_score_adjusted_dist ~ log_contributors , data = df2_subs)
summary(lm_model)

lm_model <- lm(gini_score_adjusted_dist ~ log_contributors , data = df2_subs[df2_subs$is_berlin,])
summary(lm_model)

lm_model <- lm(gini_score_adjusted_dist ~ log_contributors , data = df2_subs[df2_subs$is_de,])
summary(lm_model)

lm_model <- lm(gini_score_adjusted_dist ~ log_contributors , data = df2_subs[df2_subs$is_europe,])
summary(lm_model)
```